### ISSUE TITLE
Make `git topics finish <topic>` delete the remote branch

### ISSUE THREAD

**Issue by hsujeremyc** [ajvondrak/git-topics#3]
When running `git topics finish <topic>`, I think it'd make a lot of sense to delete the `<topic>` remote branch. At this point, that branch should be "complete" and any additional work or hotfixes or features relating to that topic should probably be started in a new topic branch.

This is mostly just for sanity in helping keep project branches in check.

**Comment by ajvondrak** [comment]
So, I actually tried this behavior out initially, but wound up moving it to `git topics release` for the reasons explained in this commit message: https://github.com/ajvondrak/git-topics/commit/17f0361239778797a04a52b2aa3cd9c82451b989 Happy to expound upon any of those reasons, if they're unclear.

**Comment by hsujeremyc** [comment]
Huh, looking at that commit makes it look like `git topics release` already does it? Could have sworn it didn't when I ran it but I'll check again.

**Comment by ajvondrak** [comment]
Random thought: you might need to run a `git remote prune origin` if a bunch of dead remote branches are still showing up (say, in a `git topics list -a`).
